{
 "title": "My dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Aqi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n            |> filter(fn: (r) => r[\"_field\"] == \"aqi\") "
    }
   ]
  },
  {
   "title": "Hum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_field\"] == \"hum\") "
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_field\"] == \"temp\") "
    }
   ]
  },
  {
   "title": "Conc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_field\"] == \"conc\") "
    }
   ]
  },
  {
   "title": "Rssi",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n            |> filter(fn: (r) => r[\"_field\"] == \"rssi\") "
    }
   ]
  },
  {
   "title": "Outdoore temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": " from(bucket: \"Air_Quality\")\r\n            |> range(start: -1d)\r\n            |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality\")\r\n            |> filter(fn: (r) => r[\"_field\"] == \"out\") "
    }
   ]
  }
 ]
}