version: "3"

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:${DOCKER_INFLUXDB_INIT_PORT}

  telegraf:
    image: telegraf-python:latest
    volumes:
      - ${TELEGRAF_CONF_PATH}:/etc/telegraf/telegraf.conf:rw
      - ${TELEGRAF_FORECAST_PATH}:/etc/telegraf/data_forecasting.py:x
      - ${TELEGRAF_LOG_PATH}:/var/log/telegraf/telegraf.log
      #- ${TELEGRAF_DATA_PATH}:/etc/telegraf/provaDati.json:r
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped
    # ports:
    #   - 8080:8080

  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ${MQTT_CONF_PATH}:/mosquitto/config/mosquitto.conf
      - ${MQTT_DATA_PATH}:/mosquitto/data/passwords.txt
      - ${MQTT_LOG_PATH}:/mosquitto/log
    restart: always
    ports:
      - ${MQTT_PORT}:${MQTT_PORT}
      - 9001:9001

volumes:
  grafana-storage: 
  influxdb-storage: 
